[package]
name = "laplace_server"
version = "0.1.0"
authors = [
    "Alexander Mescheryakov <freecoder.xx@gmail.com>",
    "Noogen Team <info.noogen@gmail.com>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/noogen-projects/laplace"
description = "The server of the local-first web-application platform"

[dependencies]
async-std = "1.9"
actix = "0.13"
actix-web = { version = "4.0.1", features = ["openssl"] }
actix-web-actors = "4.1.0"
actix-files = "0.6.0"
openssl = "0.10"
rcgen = "0.9"
arc-swap = "1.5"
bs58 = "0.4"
clap = { version = "3.0", features = ["derive"] }
borsh = "0.9"
futures = "0.3"
libp2p = { version = "0.42", features = ["tcp-tokio", "mdns"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
derive_more = "0.99"
log = "0.4"
flexi_logger = "0.22"
config = "0.11"
toml = "0.5"
wasmer = "2.1"
wasmer-wasi = "2.1"
rusqlite = { version = "0.26", features = ["bundled"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
laplace_common = { path = "../laplace_common" }
laplace_wasm = { path = "../laplace_wasm" }