[workspace]
members = [
    "examples/chat/client",
    "examples/chat/common",
    "examples/chat/server",
    "examples/echo/client",
    "examples/echo/server",
    "examples/notes/client",
    "examples/notes/common",
    "examples/notes/server",
    "examples/todo/client",
    "examples/todo/common",
    "examples/todo/server",

    "laplace_client",
    "laplace_common",
    "laplace_server",
    "laplace_wasm",
    "laplace_wasm_macro",
    "laplace_yew",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
